import { Poppins } from "next/font/google";
import "./globals.css";
import Nav from "@/components/Nav";
import SearchItems from "@/components/SearchItems";
import Footer from "@/components/Footer";
import { Slide, ToastContainer } from "react-toastify";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600"],
});

export const metadata = {
  title: "RoomKart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased `}>
        <ToastContainer
          position="top-right"
          autoClose={700}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick={false}
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
          transition={Slide}
        />
        <Nav />
        <SearchItems />
        {children}
        <Footer />
      </body>
    </html>
  );
}
